[package]
name = "spark"
version = "0.1.0"
edition = "2021"
authors = ["xvanc <xvancm@gmail.com>"]
publish = false
license = "BSD-3-Clause"
description = "A 64-bit bootloader for RISC-V"
readme = "./README.md"
repository = "https://github.com/bolt-os/spark"

[dependencies]
anyhow = { version = "1.0", default-features = false }
bitflags = "<2"
bolt-libelf = { git = "https://github.com/bolt-os/libelf" }
libsa = { git = "https://github.com/bolt-os/libsa" }
log = "0.4"
memoffset = "0.8"
fdt = "0.1"
rustc-demangle = "0.1"
sbi = "0.2"
spin = "0.9"
uuid = { version = "1.0", default-features = false }

[dependencies.limine]
git = "https://github.com/bolt-os/limine-rs"
rev = "722eef0"
features = ["bootloader"]

[dependencies.unwinding]
version = "0.1"
default-features = false
features = [ "unwinder", "fde-static", "personality", "panic" ]
